language: node_js
node_js:
  - "6"
  - "8"
  - "node"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: "npm run test-travis"
after_success: 'npm run coveralls'